import { defineConfig, presetIcons, presetTypography } from 'unocss';
import presetWind3 from '@unocss/preset-wind3';

export default defineConfig({
  presets: [
    presetWind3(),
    presetIcons({
      collections: {
        logos: () => import('@iconify-json/logos/icons.json').then((i) => i.default as any),
        uil: () => import('@iconify-json/uil/icons.json').then((l) => l.default as any),
      },
    }),
    presetTypography(),
  ],
  theme: {
    colors: {
      // Brutalist theme colors
      red: '#ff0000',
      blue: '#0000ff',
      green: '#00ff00',
      yellow: '#ffff00',
      pink: '#ff69b4',
      purple: '#800080',
      orange: '#ffa500',
      teal: '#008080',
      cyan: '#00ffff',
      lime: '#00ff00',
      emerald: '#50c878',
      fuchsia: '#ff00ff',
      violet: '#8a2be2',
      rose: '#ff69b4',
      sky: '#87ceeb',
      amber: '#ffbf00',
    },
  },
  safelist: [
    // Ensure all background color classes are generated
    'bg-red',
    'bg-blue',
    'bg-green',
    'bg-yellow',
    'bg-pink',
    'bg-purple',
    'bg-orange',
    'bg-teal',
    'bg-cyan',
    'bg-lime',
    'bg-emerald',
    'bg-fuchsia',
    'bg-violet',
    'bg-rose',
    'bg-sky',
    'bg-amber',
    // Ensure all text color classes are generated
    'text-red',
    'text-blue',
    'text-green',
    'text-yellow',
    'text-pink',
    'text-purple',
    'text-orange',
    'text-teal',
    'text-cyan',
    'text-lime',
    'text-emerald',
    'text-fuchsia',
    'text-violet',
    'text-rose',
    'text-sky',
    'text-amber',
    // Ensure all border color classes are generated
    'border-red',
    'border-blue',
    'border-green',
    'border-yellow',
    'border-pink',
    'border-purple',
    'border-orange',
    'border-teal',
    'border-cyan',
    'border-lime',
    'border-emerald',
    'border-fuchsia',
    'border-violet',
    'border-rose',
    'border-sky',
    'border-amber',
    // Ensure all hover background color classes are generated
    'hover:bg-red',
    'hover:bg-blue',
    'hover:bg-green',
    'hover:bg-yellow',
    'hover:bg-pink',
    'hover:bg-purple',
    'hover:bg-orange',
    'hover:bg-teal',
    'hover:bg-cyan',
    'hover:bg-lime',
    'hover:bg-emerald',
    'hover:bg-fuchsia',
    'hover:bg-violet',
    'hover:bg-rose',
    'hover:bg-sky',
    'hover:bg-amber',
    // Ensure all hover text color classes are generated
    'hover:text-red',
    'hover:text-blue',
    'hover:text-green',
    'hover:text-yellow',
    'hover:text-pink',
    'hover:text-purple',
    'hover:text-orange',
    'hover:text-teal',
    'hover:text-cyan',
    'hover:text-lime',
    'hover:text-emerald',
    'hover:text-fuchsia',
    'hover:text-violet',
    'hover:text-rose',
    'hover:text-sky',
    'hover:text-amber',
  ],
});
